// Code generated by pkg/update-images. DO NOT EDIT.

package cke

const (
	EtcdImage            = Image("ghcr.io/cybozu/etcd:3.6.11.1@sha256:c2e3075893ca9264773d022c4789e401c6ff7346ffd4101a4d79f3bdf37f5637")
	KubernetesImage      = Image("ghcr.io/cybozu/kubernetes:1.35.5.1@sha256:1051a9fba32c5a095c3895cb1b215d55454ee662d53147dcba56fb1cbda431ea")
	ToolsImage           = Image("ghcr.io/cybozu-go/cke-tools:1.35.0@sha256:3f0365cf68834dc9e2e082ec901495cae41c8cfc5dcaa9c3a2062d4b50a66f82")
	PauseImage           = Image("ghcr.io/cybozu/pause:3.10.1.5@sha256:3565a5a085d941c10ef86aaf2bfdaabc8c0f8677d55b2371dce472eb79a79d08")
	CoreDNSImage         = Image("ghcr.io/cybozu/coredns:1.14.2.1@sha256:e29066d55b9455fdba973ceb6f77232677de15263cc1c78f63707935adc01a14")
	UnboundImage         = Image("ghcr.io/cybozu/unbound:1.25.1.1@sha256:b84ce87568ed11859891747650a46d8431bac6d1ddda38b542e4d16cd36e0b86")
	UnboundExporterImage = Image("ghcr.io/cybozu/unbound_exporter:0.5.0.4@sha256:a7d46220f43bf2ae0c81bbcb0b68801de2d60e87df298db4691ea0dd39b25593")
)
