apiVersion: batch/v1
kind: Job
metadata:
  namespace: reboot-test
  name: job-running
spec:
  template:
    spec:
      containers:
      - name: ubuntu
        image: ghcr.io/cybozu/ubuntu:22.04
        command: ["sleep", "3600"]
      restartPolicy: Never
  backoffLimit: 1
