package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"net/url"
	"os"
	"os/exec"
	"strings"
	"text/template"
)

type imageEntry struct {
	VarName    string
	Repository string
}

// Update Repository here when adding or removing images.
var images = []imageEntry{
	{"EtcdImage", "ghcr.io/cybozu/etcd"},
	{"KubernetesImage", "ghcr.io/cybozu/kubernetes"},
	{"ToolsImage", "ghcr.io/cybozu-go/cke-tools"},
	{"PauseImage", "ghcr.io/cybozu/pause"},
	{"CoreDNSImage", "ghcr.io/cybozu/coredns"},
	{"UnboundImage", "ghcr.io/cybozu/unbound"},
	{"UnboundExporterImage", "ghcr.io/cybozu/unbound_exporter"},
}

const outputFile = "images_gen.go"

const tmpl = `// Code generated by pkg/update-images. DO NOT EDIT.

package cke

const (
{{- range .}}
	{{.VarName}} = Image("{{.Repository}}:{{.Tag}}@{{.Digest}}")
{{- end}}
)
`

type packageVersion struct {
	Name      string `json:"name"` // digest e.g. "sha256:abc..."
	CreatedAt string `json:"created_at"`
	Metadata  struct {
		Container struct {
			Tags []string `json:"tags"`
		} `json:"container"`
	} `json:"metadata"`
}

type imageResult struct {
	VarName    string
	Repository string
	Tag        string
	Digest     string
}

// fetchLatest queries the GitHub Packages API (via gh CLI) for the latest
// version of repository, returning its tag and digest.
func fetchLatest(repository string) (tag, digest string, err error) {
	withoutRegistry, _ := strings.CutPrefix(repository, "ghcr.io/")
	org, pkg, ok := strings.Cut(withoutRegistry, "/")
	if !ok {
		return "", "", fmt.Errorf("invalid repository %q: expected ghcr.io/org/package", repository)
	}

	apiPath := fmt.Sprintf("/orgs/%s/packages/container/%s/versions?per_page=100",
		org, url.PathEscape(pkg))

	out, err := exec.Command("gh", "api", apiPath, "--paginate").Output()
	if err != nil {
		return "", "", fmt.Errorf("gh api failed for %s: %w", repository, err)
	}

	var versions []packageVersion
	dec := json.NewDecoder(bytes.NewReader(out))
	for dec.More() {
		var page []packageVersion
		if err := dec.Decode(&page); err != nil {
			return "", "", fmt.Errorf("failed to decode response for %s: %w", repository, err)
		}
		versions = append(versions, page...)
	}

	// Pick the latest version that has at least one tag.
	var latest *packageVersion
	for i := range versions {
		v := &versions[i]
		if len(v.Metadata.Container.Tags) == 0 {
			continue
		}
		if latest == nil || v.CreatedAt > latest.CreatedAt {
			latest = v
		}
	}
	if latest == nil {
		return "", "", fmt.Errorf("no tagged version found for %s", repository)
	}

	// Pick the longest tag excluding "latest"
	for _, t := range latest.Metadata.Container.Tags {
		if t != "latest" && len(t) > len(tag) {
			tag = t
		}
	}
	if tag == "" {
		return "", "", fmt.Errorf("no non-latest tag found for %s", repository)
	}

	return tag, latest.Name, nil
}

func main() {
	results := make([]imageResult, len(images))
	for i, img := range images {
		tag, digest, err := fetchLatest(img.Repository)
		if err != nil {
			fmt.Fprintf(os.Stderr, "failed to fetch latest for %s: %v\n", img.Repository, err)
			os.Exit(1)
		}
		fmt.Printf("%s %s:%s -> %s\n", img.VarName, img.Repository, tag, digest)
		results[i] = imageResult{
			VarName:    img.VarName,
			Repository: img.Repository,
			Tag:        tag,
			Digest:     digest,
		}
	}

	t := template.Must(template.New("").Parse(tmpl))
	var buf bytes.Buffer
	if err := t.Execute(&buf, results); err != nil {
		fmt.Fprintf(os.Stderr, "failed to render template: %v\n", err)
		os.Exit(1)
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		fmt.Fprintf(os.Stderr, "failed to format source: %v\n", err)
		os.Exit(1)
	}

	if err := os.WriteFile(outputFile, formatted, 0644); err != nil {
		fmt.Fprintf(os.Stderr, "failed to write %s: %v\n", outputFile, err)
		os.Exit(1)
	}

	fmt.Printf("Updated %s\n", outputFile)
}
