package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"net/url"
	"os"
	"os/exec"
	"regexp"
	"strconv"
	"strings"
	"text/template"
)

type image struct {
	Name       string
	Repository string
	Tag        string
	Digest     string
}

// Update this list when adding or removing images.
var images = []*image{
	{Name: "EtcdImage", Repository: "ghcr.io/cybozu/etcd"},
	{Name: "KubernetesImage", Repository: "ghcr.io/cybozu/kubernetes"},
	{Name: "ToolsImage", Repository: "ghcr.io/cybozu-go/cke-tools"},
	{Name: "PauseImage", Repository: "ghcr.io/cybozu/pause"},
	{Name: "CoreDNSImage", Repository: "ghcr.io/cybozu/coredns"},
	{Name: "UnboundImage", Repository: "ghcr.io/cybozu/unbound"},
	{Name: "UnboundExporterImage", Repository: "ghcr.io/cybozu/unbound_exporter"},
}

const outputFile = "images_gen.go"

const tmpl = `// Code generated by hack/update-images. DO NOT EDIT.

package cke

var (
{{- range .}}
	{{.Name}} = newImage("{{.Repository}}", "{{.Tag}}", "{{.Digest}}")
{{- end}}
)

var allImages = []Image{
{{- range .}}
	{{.Name}},
{{- end}}
}
`

// versionTag matches version tags such as "1.35.9.1".
var versionTag = regexp.MustCompile(`^\d+(\.\d+)+$`)

// compareVersions compares dot-separated numeric versions.
// Both a and b must match versionTag.
func compareVersions(a, b string) int {
	as := strings.Split(a, ".")
	bs := strings.Split(b, ".")
	for i := 0; i < len(as) && i < len(bs); i++ {
		an, _ := strconv.Atoi(as[i])
		bn, _ := strconv.Atoi(bs[i])
		if an != bn {
			return an - bn
		}
	}
	return len(as) - len(bs)
}

type packageVersion struct {
	Name     string `json:"name"` // digest e.g. "sha256:abc..."
	Metadata struct {
		Container struct {
			Tags []string `json:"tags"`
		} `json:"container"`
	} `json:"metadata"`
}

// fetchLatest queries the GitHub Packages API (via gh CLI) for the highest
// version tag of img, returning the tag and its digest.
func fetchLatest(img *image) (tag, digest string, err error) {
	withoutRegistry, _ := strings.CutPrefix(img.Repository, "ghcr.io/")
	org, pkg, ok := strings.Cut(withoutRegistry, "/")
	if !ok {
		return "", "", fmt.Errorf("invalid repository %q: expected ghcr.io/org/package", img.Repository)
	}

	apiPath := fmt.Sprintf("/orgs/%s/packages/container/%s/versions?per_page=100",
		org, url.PathEscape(pkg))

	cmd := exec.Command("gh", "api", apiPath, "--paginate")
	cmd.Stderr = os.Stderr
	out, err := cmd.Output()
	if err != nil {
		return "", "", fmt.Errorf("gh api failed for %s: %w", img.Repository, err)
	}

	var versions []packageVersion
	dec := json.NewDecoder(bytes.NewReader(out))
	for dec.More() {
		var page []packageVersion
		if err := dec.Decode(&page); err != nil {
			return "", "", fmt.Errorf("failed to decode response for %s: %w", img.Repository, err)
		}
		versions = append(versions, page...)
	}

	for _, v := range versions {
		for _, t := range v.Metadata.Container.Tags {
			if !versionTag.MatchString(t) {
				continue
			}
			if tag == "" || compareVersions(t, tag) > 0 {
				tag = t
				digest = v.Name
			}
		}
	}
	if tag == "" {
		return "", "", fmt.Errorf("no version tag found for %s", img.Repository)
	}

	return tag, digest, nil
}

func main() {
	// This program must be run at the repository root, where images.go exists.
	if _, err := os.Stat("images.go"); err != nil {
		fmt.Fprintf(os.Stderr, "images.go not found; run this at the repository root: %v\n", err)
		os.Exit(1)
	}

	for _, img := range images {
		tag, digest, err := fetchLatest(img)
		if err != nil {
			fmt.Fprintf(os.Stderr, "failed to fetch latest for %s: %v\n", img.Repository, err)
			os.Exit(1)
		}
		fmt.Printf("%s %s:%s (%s)\n", img.Name, img.Repository, tag, digest)
		img.Tag = tag
		img.Digest = digest
	}

	t := template.Must(template.New("").Parse(tmpl))
	var buf bytes.Buffer
	if err := t.Execute(&buf, images); err != nil {
		fmt.Fprintf(os.Stderr, "failed to render template: %v\n", err)
		os.Exit(1)
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		fmt.Fprintf(os.Stderr, "failed to format source: %v\n", err)
		os.Exit(1)
	}

	if err := os.WriteFile(outputFile, formatted, 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "failed to write %s: %v\n", outputFile, err)
		os.Exit(1)
	}

	fmt.Printf("Updated %s\n", outputFile)
}
