package main

import (
	"bufio"
	"bytes"
	"fmt"
	"go/format"
	"io"
	"os"
	"path"
	"path/filepath"
	"strings"
	"text/template"

	utilyaml "k8s.io/apimachinery/pkg/util/yaml"
	"sigs.k8s.io/yaml"

	"github.com/cybozu-go/cke"
)

const (
	inputPattern = "*.yml"
	outputFile   = "resources.go"
)

func main() {
	err := subMain()
	if err != nil {
		fmt.Fprintln(os.Stderr, "Error:", err)
		os.Exit(2)
	}
}

func subMain() error {
	files, err := filepath.Glob(inputPattern)
	if err != nil {
		return err
	}

	images := make(map[string]string)
	for _, img := range cke.AllImages() {
		id, _, _ := strings.Cut(path.Base(img), ":")
		if prev, ok := images[id]; ok {
			return fmt.Errorf("image name %q is ambiguous: %s and %s", id, prev, img)
		}
		images[id] = img
	}

	var allResources []cke.ResourceDefinition
	keys := make(map[string]string)
	for _, fname := range files {
		res, err := loadResources(fname, images)
		if err != nil {
			return err
		}
		for _, r := range res {
			if prev, ok := keys[r.Key]; ok {
				return fmt.Errorf("duplicate resource %s in %s and %s", r.Key, prev, fname)
			}
			keys[r.Key] = fname
		}
		allResources = append(allResources, res...)
	}

	cke.SortResources(allResources)
	return renderResources(allResources)
}

func loadResources(fname string, images map[string]string) ([]cke.ResourceDefinition, error) {
	tmpl, err := template.New(filepath.Base(fname)).Option("missingkey=error").ParseFiles(fname)
	if err != nil {
		return nil, err
	}

	buf := &bytes.Buffer{}
	err = tmpl.Execute(buf, images)
	if err != nil {
		return nil, err
	}

	y := utilyaml.NewYAMLReader(bufio.NewReader(buf))
	var res []cke.ResourceDefinition
	for {
		data, err := y.Read()
		if err == io.EOF {
			return res, nil
		}
		if err != nil {
			return nil, err
		}

		key, err := cke.ParseResource(data)
		if err != nil {
			return nil, err
		}

		parts := strings.Split(key, "/")
		kind := parts[0]
		var namespace, name string
		if len(parts) == 2 {
			name = parts[1]
		} else {
			namespace = parts[1]
			name = parts[2]
		}

		obj := struct {
			Metadata struct {
				Annotations struct {
					Revision int64  `json:"cke.cybozu.com/revision,string"`
					Image    string `json:"cke.cybozu.com/image"`
				} `json:"annotations"`
			} `json:"metadata"`
		}{}
		if err := yaml.Unmarshal(data, &obj); err != nil {
			return nil, err
		}
		rev := obj.Metadata.Annotations.Revision
		if rev <= 0 {
			return nil, fmt.Errorf("%s: static resources must declare a positive cke.cybozu.com/revision in annotations", key)
		}

		res = append(res, cke.ResourceDefinition{
			Key:        key,
			Kind:       kind,
			Namespace:  namespace,
			Name:       name,
			Revision:   rev,
			Image:      obj.Metadata.Annotations.Image,
			Definition: data,
		})
	}
}

var tmpl = template.Must(template.New("").Parse(`// Code generated by hack/compile-resources. DO NOT EDIT.
//go:generate go run ../hack/compile-resources

package static

import (
	"github.com/cybozu-go/cke"
)

// Resources is the Kubernetes resource definitions embedded in CKE.
var Resources = []cke.ResourceDefinition{
	{{ range . -}}
	{
		Key: {{ printf "%q" .Key }},
		Kind: {{ printf "%q" .Kind }},
		Namespace: {{ printf "%q" .Namespace }},
		Name: {{ printf "%q" .Name }},
		Revision: {{ .Revision }},
		Image: {{ printf "%q" .Image }},
		Definition: []byte({{ printf "%q" .Definition }}),
	},
	{{ end -}}
}
`))

func renderResources(res []cke.ResourceDefinition) error {
	buf := &bytes.Buffer{}
	err := tmpl.Execute(buf, res)
	if err != nil {
		return err
	}

	src, err := format.Source(buf.Bytes())
	if err != nil {
		return err
	}

	return os.WriteFile(outputFile, src, 0o644)
}
